export const RECEIVED_COMPANIES = "RECEIVED_COMPANIES";
export const RECEIVED_COMPANY = "RECEIVED_COMPANY";

export const CART_UPDATE = "CART_UPDATE";

export const AUTH_ERROR = "AUTH_ERROR";
export const LOGGED_IN = "LOGGED_IN";
