"""empty message

Revision ID: 091d64128eec
Revises: edbc321613c0
Create Date: 2020-04-26 01:34:55.758617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091d64128eec'
down_revision = 'edbc321613c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'company', 'images', ['image_id'], ['id'])
    op.drop_constraint('images_product_id_fkey', 'images', type_='foreignkey')
    op.drop_constraint('images_company_id_fkey', 'images', type_='foreignkey')
    op.drop_column('images', 'company_id')
    op.drop_column('images', 'product_id')
    op.add_column('product', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'images', ['image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'image_id')
    op.add_column('images', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('images', sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('images_company_id_fkey', 'images', 'company', ['company_id'], ['id'])
    op.create_foreign_key('images_product_id_fkey', 'images', 'product', ['product_id'], ['id'])
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.drop_column('company', 'image_id')
    # ### end Alembic commands ###
