"""empty message

Revision ID: 0d235d6dfbda
Revises: aadc26c58952
Create Date: 2020-04-21 11:58:53.426352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d235d6dfbda'
down_revision = 'aadc26c58952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('order_id', sa.Integer(), nullable=True))
    op.drop_constraint('cart_items_item_id_fkey', 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'order', ['order_id'], ['id'])
    op.drop_column('cart_items', 'item_id')
    op.drop_constraint('order_cart_id_fkey', 'order', type_='foreignkey')
    op.drop_column('order', 'cart_id')
    op.add_column('product', sa.Column('cart_item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'cart_items', ['cart_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'cart_item_id')
    op.add_column('order', sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('order_cart_id_fkey', 'order', 'cart_items', ['cart_id'], ['id'])
    op.add_column('cart_items', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key('cart_items_item_id_fkey', 'cart_items', 'product', ['item_id'], ['id'])
    op.drop_column('cart_items', 'order_id')
    # ### end Alembic commands ###
