"""empty message

Revision ID: aadc26c58952
Revises: 0ef95f00a6fe
Create Date: 2020-04-20 16:58:30.913899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aadc26c58952'
down_revision = '0ef95f00a6fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('item_id', sa.Integer(), nullable=True))
    op.drop_constraint('cart_items_product_id_fkey', 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'product', ['item_id'], ['id'])
    op.drop_column('cart_items', 'product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key('cart_items_product_id_fkey', 'cart_items', 'product', ['product_id'], ['id'])
    op.drop_column('cart_items', 'item_id')
    # ### end Alembic commands ###
