"""empty message

Revision ID: b679f3d4f8c5
Revises: 5d0aa5bc0b51
Create Date: 2020-04-25 12:29:56.464302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b679f3d4f8c5'
down_revision = '5d0aa5bc0b51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'created_at')
    # ### end Alembic commands ###
